server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_service
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # vì bạn có file SQL riêng để tạo bảng
    show-sql: true     # hiển thị câu SQL trong terminal
    properties:
      hibernate:
        format_sql: true

  application:
    name: appointment-service
